### ISSUE TITLE
Increase FTB Infinity Server RAM

### ISSUE THREAD

**Issue by aXGAZXa** [JonasBonno/docker-ftb-infinity#1]
Hi buddy, thanks again for all your great work, I'm hosting an FTB Infinity server on my Synology NAS using your Docker build and its been going great but I need to increase the RAM that Java uses on startup and cant find how to do this, regardless of anything I try it runs as Xms -512 and Xmx -2048.
I have 16gb of RAM on the NAS and would like to increase this significantly. Any help would be much appreciated. Thanks again.

**Comment by JonasBonno** [comment]
Hi, thank you.
Normally you would do it with Docker environment variables but I have not included that in the docker images yet, but maybe I will set it up for next build.

For now you need to manually modify the server.sh or start.sh files inside the container that runs the ftb-server. 

You can go inside the running container with "docker exec -it [name of container] bash".
Inside the container you can locate both files in the /minecraft folder. 
If you e.g. need a additional text editor not installed you may need to install it with "apt-get update" and "apt-get install [package name]" e.g. vim. 
After changing the needed java settings, exit out and restart the container.

**Comment by aXGAZXa** [comment]
that got it buddy thanks, I am kind of new to this so it took a bit of poking around but I got there. Permissions have been a pain but im now on 8G, thanks again and keep up the good work.
